version: '3'
services:
  peco:
    build:
      dockerfile: dockerfile
    container_name: peco1
    volumes:
      - ./code:/root/project/code
      - ./testcases:/root/project/testcases
      - ./log:/root/project/log